data:
  dataset: imagenette
  kwargs:
    normalize: True
    batch_size: 8
    image_mode: Y
    random_flip: True
model:
  mode: F
  activation: ReLU
  batch_norm: False
nested_dropout:
  apply_nested_dropout: False
  optimize_dropout: nan
  freeze_gradients: nan
  p: nan
  sequence_bound: nan
  tol: nan
optim:
  optimizer: nan
  optimizer_kwargs:
    lr: nan  # Learning rate
  lr_scheduler: StepLR
  lr_scheduler_kwargs:
    step_size: 1
    gamma: 0.98
    verbose: False
train:
  loss_criterion: MSELoss
  epochs: 100
  plateau_limit: None
