data:
  dataset: imagenette
  kwargs:
    normalize: True
    batch_size: 64  # important
    image_mode: Y
    random_flip: True
model:
  mode: F
  activation: ReLU
  batch_norm: False
nested_dropout:
  apply_nested_dropout: True # important
  optimize_dropout: True
  freeze_gradients: True
  p: 0.1
  tol: 1.e-4
optim:
  optimizer: Adam
  optimizer_kwargs:
    lr: 1.e-3  # important
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_kwargs:
    patience: 10
train:
  loss_criterion: MSELoss
  epochs: 100
  plateau_limit: None
