data:
  dataset: imagenette
  kwargs:
    normalize: True
    batch_size: 16
    image_mode: Y
    random_flip: True
model:
  mode: F
  activation: ReLU
  batch_norm: False
nested_dropout:
  apply_nested_dropout: True
  p: 0.1
  sequence_bound: 32
  tol: 1.e-5
optim:
  optimizer: Adam
  optimizer_kwargs:
    lr: 1.e-3  # Learning rate
#  lr_scheduler: ReduceLROnPlateau
#  lr_scheduler_kwargs:
#    mode: min
#    patience: 5
#    verbose: True
  lr_scheduler: StepLR
  lr_scheduler_kwargs:
    step_size: 1
    gamma: 0.98
    verbose: True
train:
  loss_criterion: MSELoss
  epochs: 100
  plateau_limit: None
